<?php
/**
 * admin/includes/kategori_seed_data.php
 * Data REKOMENDASI kategori (referensi) — dikurasi dari EPOIN SMPN 1 Gunungtanjung.
 * Dipakai tombol "Muat Rekomendasi" di prestasi.php & pelanggaran.php.
 * Sekolah bebas memakai sebagian, semua, atau menghapus semuanya.
 */

$SEED_PRESTASI = [
    ['nama' => 'Prestasi Kejuaraan/Lomba Tingkat Nasional/Internasional', 'point' => 50],
    ['nama' => 'Juara Umum 1-3', 'point' => 40],
    ['nama' => 'Prestasi Kejuaraan/Lomba Tingkat Provinsi', 'point' => 35],
    ['nama' => 'Juara Kelas 1-3', 'point' => 25],
    ['nama' => 'Prestasi Kejuaraan/Lomba Tingkat Kabupaten', 'point' => 25],
    ['nama' => 'Juara Kelas 4-5', 'point' => 20],
    ['nama' => 'Prestasi Kejuaraan/Lomba Tingkat Kecamatan', 'point' => 20],
    ['nama' => 'Tidak melakukan pelanggaran selama 60 hari berturut-turut', 'point' => 20],
    ['nama' => 'Kehadiran 100% tanpa alpa dan tanpa terlambat dalam 1 semester', 'point' => 20],
    ['nama' => 'Juara Kelas 6-10', 'point' => 15],
    ['nama' => 'Prestasi Kejuaraan/Lomba Tingkat Sekolah', 'point' => 15],
    ['nama' => 'Membawa nama baik sekolah di media (misalnya berita positif, konten kreatif bermanfaat)', 'point' => 15],
    ['nama' => 'Membuat karya berbasis IT (video, animasi, coding, media belajar)', 'point' => 15],
    ['nama' => 'Mengharumkan nama sekolah di luar kegiatan akademik', 'point' => 15],
    ['nama' => 'Mentor ekstrakurikuler bagi adik kelas', 'point' => 15],
    ['nama' => 'Peraih TKK/TKU pramuka (lencana kecakapan tertentu)', 'point' => 15],
    ['nama' => 'Penulis artikel buletin/website sekolah', 'point' => 15],
    ['nama' => 'Bendahara Tertib Iuran Kas Ã¢â‚¬â€ capaian iuran kelas Ã¢â€°Â¥95% sebelum jatuh tempo', 'point' => 15],
    ['nama' => 'Sekretaris Rapi Administrasi Ã¢â‚¬â€ Notulen/agenda lengkap & absensi Ã¢â€°Â¤24 jam tiap pertemuan', 'point' => 15],
    ['nama' => 'Pengurus Aktif OSIS (ketua/sekretaris/bendahara) selama 1 semester, hadir latihan/rapat, mengelola minimal 1 program/kegiatan; disahkan Pembina OSIS', 'point' => 10],
    ['nama' => 'Pengurus Aktif Ekstrakurikuler (ketua/sekretaris/bendahara) selama 1 semester, hadir latihan/rapat, mengelola minimal 1 program/kegiatan; disahkan Pembina Ekskul', 'point' => 10],
    ['nama' => 'Mewakili sekolah dalam kegiatan/acara tertentu', 'point' => 10],
    ['nama' => 'Siswa Teladan Bulanan (disiplin, sopan, rajin)', 'point' => 10],
    ['nama' => 'Kontributor aktif di mading/majalah sekolah', 'point' => 10],
    ['nama' => 'Siswa yang paling banyak meminjam/membaca buku perpustakaan.', 'point' => 10],
    ['nama' => 'Memberikan ide bermanfaat untuk kegiatan sekolah', 'point' => 10],
    ['nama' => 'Duta literasi (menulis & memajang resensi buku di mading/perpus)', 'point' => 10],
    ['nama' => 'Panitia acara sekolah (class meeting/porseni/penerima tamu)', 'point' => 10],
    ['nama' => 'Inovasi kebersihan/ketertiban kelas (rak sepatu, label loker, dsb.)', 'point' => 10],
    ['nama' => 'Ketua Kelas / KM Teladan Ã¢â‚¬â€ rapat/briefing mingguan jalan, aduan kelas terselesaikan Ã¢â€°Â¥90%', 'point' => 10],
    ['nama' => 'Kelas Terbersih mingguan (rubrik 5 aspek, bukti foto & ceklist) Ã¢â‚¬â€ 10 poin/anggota.', 'point' => 10],
    ['nama' => 'Memberikan informasi valid terkait pelanggaran', 'point' => 5],
    ['nama' => 'Berani tampil presentasi, aktif bertanya, serta berpartisipasi dalam kegiatan sekolah maupun lomba mewakili kelas', 'point' => 5],
    ['nama' => 'Koordinator piket teladan (kelas bersih & rapi selama 1 bulan)', 'point' => 5],
    ['nama' => 'MC/pembawa acara kegiatan sekolah / menjadi petugas upacara', 'point' => 5],
    ['nama' => 'Siswa memberi bantuan nyata kepada guru di luar tugas rutin (mis. menyiapkan alat, membantu administrasi/kegiatan), atas permintaan/izin guru, terekam dan diverifikasi', 'point' => 5],
    ['nama' => 'Sekretaris/Wakil Sekretaris Kelas menyelesaikan input / verifikasi absensi dengan tepat waktu selama 1 minggu', 'point' => 5],
    ['nama' => 'Penulis cerpen/puisi dimuat di mading', 'point' => 3],
];

$SEED_PELANGGARAN = [
    ['nama' => 'Bertato (permanen)', 'point' => 100],
    ['nama' => 'Terlibat penyimpangan perilaku seksual', 'point' => 100],
    ['nama' => 'Peserta didik hamil / menghamili', 'point' => 100],
    ['nama' => 'Menikah saat masih sekolah', 'point' => 100],
    ['nama' => 'Membawa/mengkonsumsi miras/narkoba', 'point' => 100],
    ['nama' => 'Melakukan pemukulan pada kepala sekolah/pendidik', 'point' => 100],
    ['nama' => 'Membawa/mengedarkan konten pornograf', 'point' => 75],
    ['nama' => 'Berjudi, mencuri, atau perbuatan tercela lainnya', 'point' => 75],
    ['nama' => 'Berkelahi menggunakan senjata tajam/api', 'point' => 75],
    ['nama' => 'Membawa senjata tajam (walau tidak dipakai berkelahi)', 'point' => 60],
    ['nama' => 'Tindakan / perbuatan mengarah asusila', 'point' => 50],
    ['nama' => 'Memalsu tanda tangan/stempel sekolah', 'point' => 50],
    ['nama' => 'Menjadi anggota perkumpulan terlarang / geng motor', 'point' => 50],
    ['nama' => 'Memaksa teman untuk memberi uang/barang (pemalakan)', 'point' => 45],
    ['nama' => 'Menyimpan konten negatif di HP/alat elektronik (game judi, gambar tidak pantas, dll)', 'point' => 45],
    ['nama' => 'Mengakses situs terlarang di area sekolah', 'point' => 45],
    ['nama' => 'Membawa petasan/mercon/alat berbahaya', 'point' => 40],
    ['nama' => 'Melakukan perundungan online (cyberbullying) terhadap teman/guru', 'point' => 40],
    ['nama' => 'Membawa orang luar masuk ke area sekolah tanpa prosedur/izin', 'point' => 40],
    ['nama' => 'Mencemarkan nama baik sekolah/staf', 'point' => 35],
    ['nama' => 'Bertindak tidak sopan terhadap guru/staf', 'point' => 35],
    ['nama' => 'Mengintimidasi teman agar takut/tertekan (bullying non-fisik)', 'point' => 35],
    ['nama' => 'Menyalahgunakan seragam sekolah untuk hal tidak pantas di luar sekolah', 'point' => 35],
    ['nama' => 'Memalsukan keterangan sakit/izin dari orang tua', 'point' => 35],
    ['nama' => 'Menyimpan barang terlarang (korek, vape, dll) walau tidak dipakai', 'point' => 35],
    ['nama' => 'Merokok/membawa rokok di lingkungan sekolah', 'point' => 30],
    ['nama' => 'Mengunggah (upload) foto, gambar, atau tulisan yang tidak pantas di media sosial', 'point' => 30],
    ['nama' => 'Menggunakan bahasa kasar di media sosial yang merugikan sekolah/teman', 'point' => 30],
    ['nama' => 'Menyalahgunakan identitas sekolah untuk kepentingan pribadi', 'point' => 30],
    ['nama' => 'Mengajak teman kabur dari sekolah', 'point' => 30],
    ['nama' => 'Merokok di tempat umum dengan mengenakan seragam sekolah mencoreng nama baik sekolah', 'point' => 30],
    ['nama' => 'Berkelahi (tanpa senjata)', 'point' => 25],
    ['nama' => 'Membawa/Menggunakan HP/Tablet tanpa izin', 'point' => 25],
    ['nama' => 'Mengabaikan surat panggilan sekolah', 'point' => 25],
    ['nama' => 'Keluar/Masuk lingkungan sekolah dengan meloncat pagar', 'point' => 25],
    ['nama' => 'Menyebarkan gosip/fitnah yang merugikan teman/guru', 'point' => 25],
    ['nama' => 'Sengaja tidak masuk ujian/ulangan', 'point' => 25],
    ['nama' => 'Menghina atau mengejek petugas kebersihan/satpam sekolah', 'point' => 25],
    ['nama' => 'Mengabaikan peringatan guru berulang kali', 'point' => 25],
    ['nama' => 'Menggunakan laptop/HP untuk menonton film/video saat KBM', 'point' => 25],
    ['nama' => 'Tidak mematuhi tata tertib saat kegiatan studi wisata/karya wisata', 'point' => 25],
    ['nama' => 'Menggunakan fasilitas laboratorium/ruang khusus tanpa izin', 'point' => 20],
    ['nama' => 'Membawa kendaraan tanpa izin/dititipkan bukan di parkiran sekolah', 'point' => 20],
    ['nama' => 'Menggangu kegiatan keagamaan teman (misalnya saat sholat/doa/tadarus)', 'point' => 20],
    ['nama' => 'Bermain game online saat jam pelajaran', 'point' => 20],
    ['nama' => 'Membawa/mengendarai kendaraan bermotor tanpa helm', 'point' => 20],
    ['nama' => 'Berpacaran atau berduaan di area sekolah', 'point' => 20],
    ['nama' => 'Membuat laporan palsu atau memberikan informasi bohong terkait pelanggaran siswa lain, sehingga menimbulkan kesalahpahaman atau merugikan pihak lain.', 'point' => 20],
    ['nama' => 'Mengambil barang teman tanpa izin', 'point' => 15],
    ['nama' => 'Merusak tanaman/taman sekolah', 'point' => 15],
    ['nama' => 'Menggambar/menempel stiker tanpa izin di meja, kursi, atau dinding', 'point' => 15],
    ['nama' => 'Menyalakan HP di kelas saat pelajaran tanpa izin', 'point' => 15],
    ['nama' => 'Menggunakan speaker/alat musik dengan suara keras di sekolah tanpa izin', 'point' => 15],
    ['nama' => 'Menjiplak karya/tugas teman (plagiarisme)', 'point' => 15],
    ['nama' => 'Mengotori papan tulis/meja guru dengan coretan', 'point' => 15],
    ['nama' => 'Membawa speaker/alat elektronik tanpa keperluan pelajaran', 'point' => 15],
    ['nama' => 'Membuat keributan saat upacara', 'point' => 15],
    ['nama' => 'Meninggalkan barisan saat upacara tanpa izin', 'point' => 15],
    ['nama' => 'Tidak melaksanakan tugas OSIS/ekstrakurikuler padahal punya tanggung jawab', 'point' => 15],
    ['nama' => 'Menolak mengikuti arahan guru pembina kegiatan', 'point' => 15],
    ['nama' => 'Melecehkan secara verbal (body shaming, ejekan fisik)', 'point' => 15],
    ['nama' => 'Memindahkan/melepas inventaris kelas tanpa izin (kursi/meja/remote proyektor, dsb.)', 'point' => 15],
    ['nama' => 'Meninggalkan sekolah tanpa izin (membolos)', 'point' => 10],
    ['nama' => 'Bolos tidak masuk pelajaran tertentu', 'point' => 10],
    ['nama' => 'Tidak mengikuti kegiatan kerohanian sholat berjamaah dzuhur tanpa alasan yang jelas', 'point' => 10],
    ['nama' => 'Membuat gaduh saat KBM', 'point' => 10],
    ['nama' => 'Meninggalkan kelas/berada di kantin saat KBM', 'point' => 10],
    ['nama' => 'Memarkir kendaraan tidak pada tempatnya', 'point' => 10],
    ['nama' => 'Mengendarai motor dengan ugal-ugalan / Kendaraan knalpot tidak standar', 'point' => 10],
    ['nama' => 'Merusak / mencoret sarana prasarana / main bola di kelas', 'point' => 10],
    ['nama' => 'Tidak mengikuti upacara', 'point' => 10],
    ['nama' => 'Tidak mengikuti kegiatan kerohanian (duha & tadarus bersama) tanpa keterangan', 'point' => 10],
    ['nama' => 'Tidak masuk sekolah (Alpa)', 'point' => 10],
    ['nama' => 'Mengecat rambut selain warna hitam', 'point' => 10],
    ['nama' => 'Bermake up di sekolah', 'point' => 10],
    ['nama' => 'Memakai pakaian olahraga di kelas (bukan pelajaran olahraga)', 'point' => 10],
    ['nama' => 'Mengejek dengan menyebut nama orang tua', 'point' => 10],
    ['nama' => 'Melempar barang ke arah teman di kelas', 'point' => 10],
    ['nama' => 'Mengganggu konsentrasi teman saat belajar (bercanda berlebihan, usil)', 'point' => 10],
    ['nama' => 'Mengotori fasilitas umum (toilet, mushola, perpustakaan)', 'point' => 10],
    ['nama' => 'Menata rambut dengan model berlebihan (spike, mohawk, undercut ekstrem, dsb) yang tidak sesuai tata tertib sekolah', 'point' => 10],
    ['nama' => 'Keluar kelas saat KBM tanpa izin guru ', 'point' => 10],
    ['nama' => 'Tidak ikut kerja bakti/piket tanpa alasan jelas', 'point' => 10],
    ['nama' => 'Membawa korek api/lighter tanpa alasan', 'point' => 10],
    ['nama' => 'Menolak menjalankan tugas piket kelas', 'point' => 10],
    ['nama' => 'Menghindari tugas kelompok dengan sengaja', 'point' => 10],
    ['nama' => 'Tidak memakai atribut pramuka lengkap saat kegiatan / tidak memakai topi saat upacara', 'point' => 10],
    ['nama' => 'Terlambat mengembalikan buku perpustakaan / meminjam tanpa prosedur', 'point' => 10],
    ['nama' => 'Membiarkan AC/kipas/lampu/proyektor menyala setelah selesai digunakan (pemborosan energi)', 'point' => 10],
    ['nama' => 'Makan/minum di perpustakaan atau laboratorium', 'point' => 10],
    ['nama' => 'Mencoret atau merusak pakaian/atribut sekolah milik teman"', 'point' => 10],
    ['nama' => 'Tidak memakai alas kaki (sepatu/sandal), dari kelas ke masjid saat kegiatan kerohanian', 'point' => 10],
    ['nama' => 'Membuat kegaduhan di masjid saat kegiatan kerohanian (duha, tadarus, atau sholat berjamaah)', 'point' => 10],
    ['nama' => 'Tidak melaksanakan piket kelas membersihkan masjid dan tempat wudhu sesuai jadwal', 'point' => 10],
    ['nama' => 'Berangkat dari rumah tetapi tidak pernah tiba di sekolah, tanpa pemberitahuan yang sah dari orang tua/wali (membolos)', 'point' => 10],
    ['nama' => 'Mengunggah (upload)  foto atau video di lingkungan sekolah melalui media sosial yang tidak berhubungan dengan kegiatan pembelajaran maupun kegiatan sekolah resmi, sehingga dapat mengganggu citra sekolah dan konsentrasi belajar.', 'point' => 10],
    ['nama' => 'Melakukan tindakan keisengan atau bercanda secara berlebihan yang mengganggu kenyamanan, ketertiban, atau aktivitas belajar teman sekelas', 'point' => 10],
    ['nama' => 'Terlambat Datang Ke Sekolah', 'point' => 5],
    ['nama' => 'Baju dikeluarkan (selain yang dikecualikan/busana muslim/wanita seragam pramuka)', 'point' => 5],
    ['nama' => 'Membaca komik / sejenisnya saat KBM', 'point' => 5],
    ['nama' => 'Bermain kartu / sejenisnya di sekolah', 'point' => 5],
    ['nama' => 'Mencontek / kerjasama saat ujian', 'point' => 5],
    ['nama' => 'Duduk di atas meja', 'point' => 5],
    ['nama' => 'Berkomunikasi lewat jendela saat KBM', 'point' => 5],
    ['nama' => 'Berkata jorok / kasar / sifatnya menghina, mengejek, melecehkan', 'point' => 5],
    ['nama' => 'Terlambat masuk sekolah/kegiatan belajar', 'point' => 5],
    ['nama' => 'Tidak mengerjakan/menyerahkan tugas', 'point' => 5],
    ['nama' => 'Tidak membawa buku pelajaran sesuai jadwal', 'point' => 5],
    ['nama' => 'Tidak mengikuti ekstrakurikuler tanpa keterangan', 'point' => 5],
    ['nama' => 'Izin tidak masuk sekolah lebih dari 3 hari', 'point' => 5],
    ['nama' => 'Pakaian/atribut tidak lengkap atau tidak sesuai', 'point' => 5],
    ['nama' => 'Siswa/i memakai aksesoris lain / memakai perhiasan berlebihan / memakai topi selain topi sekolah', 'point' => 5],
    ['nama' => 'Memakai ikat pinggang/kaos kaki/sepatu tidak sesuai', 'point' => 5],
    ['nama' => 'Kuku panjang', 'point' => 5],
    ['nama' => 'Memakai jaket/sweater/topi di lingkungan sekolah ketika KBM', 'point' => 5],
    ['nama' => 'Memakai sepatu selain warna hitam / Sepatu Wanita Flatshoes Gaya / Pita', 'point' => 5],
    ['nama' => 'Memakai sandal (tanpa alasan sakit)', 'point' => 5],
    ['nama' => 'Siswa laki-laki berambut gondrong/tidak rapi', 'point' => 5],
    ['nama' => 'Membuat suara berlebihan (teriak, ketok meja, peluit, dsb)', 'point' => 5],
    ['nama' => 'Menggunakan listrik/colokan sekolah untuk kepentingan pribadi tanpa izin', 'point' => 5],
    ['nama' => 'Tidak memakai atribut masker/kebersihan (jika diwajibkan sekolah)', 'point' => 5],
    ['nama' => 'Meninggalkan sampah di kelas setelah pelajaran selesai', 'point' => 5],
    ['nama' => 'Makan/minum di kelas saat pelajaran berlangsung', 'point' => 5],
    ['nama' => 'Tidur di kelas saat KBM tanpa izin', 'point' => 5],
    ['nama' => 'Tidak membawa alat tulis/perlengkapan belajar', 'point' => 5],
    ['nama' => 'Membawa mainan yang mengganggu KBM (misalnya spinner, laser, dll)', 'point' => 5],
    ['nama' => 'Membawa minuman bersoda/energi berlebihan ke sekolah', 'point' => 5],
    ['nama' => 'Membuang makanan/minuman sembarangan', 'point' => 5],
    ['nama' => 'Meninggalkan sampah plastik sekali pakai di halaman sekolah', 'point' => 5],
    ['nama' => 'Menggunakan parfum berlebihan sehingga mengganggu', 'point' => 5],
    ['nama' => 'Terlambat kembali ke kelas setelah istirahat/bel berbunyi ', 'point' => 5],
    ['nama' => 'Mengunyah permen karet dan/atau menempelkan permen karet di meja/kursi', 'point' => 5],
    ['nama' => 'Membiarkan Kelas dan halaman kotor karena tidak ada siswa yang membersihkan (sanksi kolektif 1 kelas) 5 poin/siswa', 'point' => 5],
    ['nama' => 'Siswi tidak melaksanakan kebersihan kelas dan lingkungan sebagai pengganti ketidakhadiran dalam kegiatan kerohanian (haid)', 'point' => 5],
    ['nama' => 'Meminum minuman berwarna pada program KAMIS SEHAT', 'point' => 5],
    ['nama' => 'Tidak Membawa Al Quran Ketika kegiatan Kerohanian ', 'point' => 5],
    ['nama' => 'Membuang sampah sembarangan', 'point' => 3],
];

